git-issues add switched to using a hash for filename, as opposed to sequential. To avoid decentralized issues.

diff --git a/git-issues b/git-issues
--- a/git-issues
+++ b/git-issues
@@ -99,6 +99,27 @@ if [ "$1" = 'add' ]; then
     exit 0
   fi
 
+  if [ $(whereis cut | wc -c) = '5' ]; then
+    echo 'Could not find cut.' 1>&2
+    echo '' 1>&2
+    echo 'Is it installed?' 1>&2
+    exit 1
+  fi
+
+  if [ $(whereis tr | wc -c) = '4' ]; then
+    echo 'Could not find tr.' 1>&2
+    echo '' 1>&2
+    echo 'Is it installed?' 1>&2
+    exit 1
+  fi
+
+  if [ $(whereis sha512sum | wc -c) = '11' ]; then
+    echo 'Could not find sha512sum.' 1>&2
+    echo '' 1>&2
+    echo 'Is it installed?' 1>&2
+    exit 1
+  fi
+
   title="$2"
   if [ -z "$2" ]; then
     echo 'Please supply a title for your issue.' 1>&2
@@ -122,14 +143,16 @@ if [ "$1" = 'add' ]; then
     echo 'e.g. "git config --global user.email `joe.smith@example.com`"'
     exit 1
   fi
-  last_issue_no=$(ls "$git_dir/ISSUES" | sort | tail -n1 | awk -F'-' '{print $1}' )
-  if [ -z "$last_issue_no" ]; then
-    last_issue_no='0'
-  fi
-  current_issue_no=$(echo "$last_issue_no + 1" | bc)
+  # Can't use sequential issue numbers, because conflicts.
+  # So... Hash username+useremail+epochtime should be unique most of the time!
+  now=$(date +%s)
+  # We do cut the hash size, which reduces entropy considerably, but it's to be
+  # reasonable about commit message sizes.
+  hash=$(echo "$user <user_email> #$now" | sha512sum | cut -c -20)
+
   # Got our title and issue number, create the issue!
   file_name=$(echo "$title" | tr " " "-" | tr '[:upper:]' '[:lower:]')
-  file_name="$git_dir/ISSUES/$current_issue_no-$file_name.issue"
+  file_name="$git_dir/ISSUES/$hash-$file_name.issue"
   if [ -z "$3" ]; then
     echo "# $title" >> "$file_name"
     echo '' >> "$file_name"
@@ -146,7 +169,7 @@ if [ "$1" = 'add' ]; then
     echo '-- Signed: ' "$user <$user_email>" >> "$file_name"
   fi
   git add "$file_name"
-  git commit -am "[ISSUE] #$current_issue_no opened ($title) by $user <$user_email>."
+  git commit -am "[ISSUE] #$hash ($title) by $user <$user_email>."
 fi
 
 if [ "$1" = 'close' ]; then
