Implemented first version of git-issues close

diff --git a/git-issues b/git-issues
--- a/git-issues
+++ b/git-issues
@@ -156,6 +156,7 @@ if [ "$1" = 'add' ]; then
   hash=$(echo "$user <user_email> #$now" | sha512sum | cut -c -20)
 
   # Got our title and issue number, create the issue!
+  # If you change this, be sure to change the title matcher in git-issues close as well.
   file_name=$(echo "$title" | tr " " "-" | tr '[:upper:]' '[:lower:]')
   file_name="$git_dir/ISSUES/$hash-$file_name.issue"
   if [ -z "$3" ]; then
@@ -183,13 +184,68 @@ if [ "$1" = 'close' ]; then
     exit 0
   fi
 
-  # Try and match any hash
-  hash_files=$(find "$git_dir/ISSUES/" -type f -name "$2*.issue")
-  echo "$hash_files"
-  exit 1
+  user=$(git config 'user.name')
+  if [ -z "$user" ]; then
+    echo 'Could not find a git user name.' 1>&2
+    echo '' 1>&2
+    echo 'Did you set one with "git --config"?' 1>&2
+    echo 'e.g. "git config --global user.name `Joe Smith`"'
+    exit 1
+  fi
+  user_email=$(git config 'user.email')
+  if [ -z "$user" ]; then
+    echo 'Could not find a git user email address.' 1>&2
+    echo '' 1>&2
+    echo 'Did you set one with "git --config"?' 1>&2
+    echo 'e.g. "git config --global user.email `joe.smith@example.com`"'
+    exit 1
+  fi
 
-  # Try and match any title
-  title_files=$(find "$git_dir/ISSUES/" -type f -name "*-$2*.issue")
+  # Try and match any hash
+  hash_files=$(find "$git_dir/ISSUES/" -type f -name "$2-*.issue")
+  file_list="$hash_files"
+  # Hash didn't match, try titles:
+  if [ -z "$hash_files" ]; then
+    # Try and match any title
+    title=$(echo "$2" | tr " " "-" | tr '[:upper:]' '[:lower:]')
+    title_files=$(find "$git_dir/ISSUES/" -type f -name "*-$title*.issue")
+    file_list="$title_files"
+  fi
+  # Remove empty lines
+  file_list=$(echo "$file_list" | sed '/^$/d')
+
+  # If we've only got one result, we can close it.
+  if [ $(echo "$file_list" | wc -l) -eq 1 ] && [ -n "$file_list" ]; then
+    echo '' >> "$file_list"
+    if [ -z "$3" ]; then
+      echo 'CLOSED ISSUE.' >> "$file_list"
+    else
+      echo 'CLOSED ISSUE.' >> "$file_list"
+      echo '' >> "$file_list"
+      echo "$3" >> "$file_list"
+    fi
+    echo '' >> "$file_list"
+    echo '---' >> "$file_list"
+    echo '' >> "$file_list"
+    echo '-- Signed: ' "$user <$user_email>" >> "$file_list"
+    mv "$file_list" "$file_list".closed
+  else
+    if [ -z "$file_list" ]; then
+      # We got no results.
+      echo 'Search found no open issues matching that description.' 1>&2
+      echo '' 1>&2
+      echo 'Are you sure it exists?' 1>&2
+    else
+      # We got ambiguous results. Let the user deal with it.
+      echo 'Search matched multiple issues:' 1>&2
+      echo "$file_list" 1>&2
+      echo '' 1>&2
+      echo 'git-issues cannot close it.' 1>&2
+      echo 'Try searching by hash, or in the rare event of a hash clash, try renaming one of the files in question.' 1>&2
+    fi
+  fi
+
+  exit 1
 fi
 
 if [ "$1" = 'comment' ]; then
