Added install and uninstall

diff --git a/git-issues b/git-issues
--- a/git-issues
+++ b/git-issues
@@ -34,6 +34,20 @@ git_issues_dir=$(dirname "$($rlink -f "$0")")
 # FIX: ISSUEHASH Comment
 # Then autoclose it, and notify the user in a PAGER screen, so they see it.
 
+# Uninstall runs from a provided makefile!
+if [ "$1" = 'uninstall' ]; then
+
+  if [ $(whereis make | wc -c) = '6' ]; then
+    echo 'Could not find make.' 1>&2
+    echo '' 1>&2
+    echo 'Is it installed?' 1>&2
+    exit 1
+  fi
+
+  cd "$git_issues_dir"
+  make uninstall
+fi
+
 if [ "$1" = 'tui' ]; then
   echo 'NOT YET IMPLEMENTED' 1>&2
   exit 1
